# enable/disable patches

# Cancel session login if player is connecting from `localhost`
authme-geyser: false

# Do not send message to discord chat if player is soft-muted
discordsrv-griefprevention: false

# Replace `%nickname%` placeholder with player nickname
discordsrv-chat: false

# Protects player after teleport (command, plugin, unknown)
# tp_protection_ignoreCooldown is the time needed to wait to get protection again.
tp_protection: false
tp_protection_cooldown: 30
tp_protection_ignoreCooldown: 35

# Hides user that are spectators
dynmap_spectator_hide: false

# Player tag remover
player_tag_remover: false
tags_to_remove: []

# Resets player weather weather when uses riptide trident
riptide_fix: false

# When true CO will not log login commands and commands with passwords
coreprotect_login: false
# Command regex
coreprotect_loginr: "(^/login\\s{1})|(^/l\\s{1})|(^/changepass\\s{1})|(^/changepassword\\s{1})"