name: PelarPatches
author: 0x536F6170
version: '1.0'
api-version: 1.17
main: ee.pelar.PelarPatches.Main
description: Patches for Pelar server
softdepend: ['AuthMe', 'DiscordSRV', 'GriefPrevention', 'dynmap']
commands:
  pelarpunish:
    description: Generates DKBans command with uuid instead of p-name.
    usage: /pp [Player]
    permission: dkbans.command.playerInfo
    aliases:
      - pp