name: PelarPatches
author: 0x536F6170
version: '1.0'
api-version: 1.17
main: ee.pelar.PelarPatches.Main
description: Patches for Pelar server
softdepend: ['AuthMe', 'DiscordSRV', 'GriefPrevention', 'dynmap', 'CoreProtect']